changelog:
  categories:
    - title: Features, Bugfixes, etc.
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
