name: Trigger end-to-end tests on external PR approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    name: Trigger end-to-end tests
    # If reviewed by a repo(/org) owner
    if: |
      github.event.pull_request.author_association != 'MEMBER'
      && github.event.review.author_association == 'MEMBER'
      && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Launch e2e tests
        run: gh workflow --repo py-cov-action/python-coverage-comment-action run e2e-external-phase-2.yml -f PR_NUMBER=${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}
